# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService

end

target 'Rocket.Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rocket.Chat

end

target 'RocketChatRN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RocketChatRN

end

target 'ShareRocketChatRN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareRocketChatRN

end
